services:
  db:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: smse-backend:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./tmp:/app/tmp
      - ./.checkpoints:/app/.checkpoints

  worker:
    image: smse-backend:latest
    restart: unless-stopped
    command: celery -A smse_backend.celery_worker.celery worker --loglevel=info --concurrency=1
    depends_on:
      - db
      - redis
      - backend
    env_file:
      - .env
    volumes:
      - ./tmp:/app/tmp
      - ./.checkpoints:/app/.checkpoints
    deploy:
      resources:
        limits:
          memory: 13G

  migrate:
    image: smse-backend:latest
    command: flask db upgrade
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      - db
    env_file:
      - .env
    profiles:
      - migrate

volumes:
  db_data:
  redis_data:
