"""empty message

Revision ID: 070414f2e1a7
Revises: 86f6598a9ddd
Create Date: 2025-03-03 04:08:21.515134

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '070414f2e1a7'
down_revision = '86f6598a9ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index('ix_queries_user_id')
        batch_op.create_index(batch_op.f('ix_queries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queries_user_id'))
        batch_op.create_index('ix_queries_user_id', ['user_id'], unique=True)

    # ### end Alembic commands ###
