"""initial

Revision ID: 3a61afcf31ae
Revises: 
Create Date: 2024-12-13 01:42:18.194463

"""

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = "3a61afcf31ae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_name", sa.String(length=50), nullable=False),
        sa.Column("modality", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.vector.VECTOR(dim=328), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vector"),
    )
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_embeddings_model_id"), ["model_id"], unique=True
        )

    op.create_table(
        "contents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_path", sa.String(length=250), nullable=False),
        sa.Column("content_tag", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("embedding_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["embedding_id"], ["embeddings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_path"),
    )
    with op.batch_alter_table("contents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contents_embedding_id"), ["embedding_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_contents_user_id"), ["user_id"], unique=True
        )

    op.create_table(
        "queries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("text", sa.String(length=250), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("embedding_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["embedding_id"], ["embeddings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("queries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_queries_embedding_id"), ["embedding_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_queries_user_id"), ["user_id"], unique=True
        )

    op.create_table(
        "search_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column(
            "retrieved_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["contents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["query_id"], ["queries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("search_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_search_records_content_id"), ["content_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_search_records_query_id"), ["query_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_records_query_id"))
        batch_op.drop_index(batch_op.f("ix_search_records_content_id"))

    op.drop_table("search_records")
    with op.batch_alter_table("queries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_queries_user_id"))
        batch_op.drop_index(batch_op.f("ix_queries_embedding_id"))

    op.drop_table("queries")
    with op.batch_alter_table("contents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contents_user_id"))
        batch_op.drop_index(batch_op.f("ix_contents_embedding_id"))

    op.drop_table("contents")
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_embeddings_model_id"))

    op.drop_table("embeddings")
    op.drop_table("users")
    op.drop_table("models")
    # ### end Alembic commands ###
