"""empty message

Revision ID: 86f6598a9ddd
Revises: 3119415bcb82
Create Date: 2025-03-03 01:43:51.597611

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '86f6598a9ddd'
down_revision = '3119415bcb82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_records', schema=None) as batch_op:
        batch_op.drop_index('ix_search_records_query_id')
        batch_op.create_index(batch_op.f('ix_search_records_query_id'), ['query_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_records_query_id'))
        batch_op.create_index('ix_search_records_query_id', ['query_id'], unique=True)

    # ### end Alembic commands ###
