"""add modality field to embeddings table

Revision ID: c5c3be8af83d
Revises: e4835d7ab10b
Create Date: 2025-05-19 18:21:01.059511

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = 'c5c3be8af83d'
down_revision = 'e4835d7ab10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modality', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_column('modality')

    # ### end Alembic commands ###
