"""set content.user_id unique attribute to False

Revision ID: da28b66f399d
Revises: 9ec95ec6fcd3
Create Date: 2024-12-25 22:25:23.490647

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = 'da28b66f399d'
down_revision = '9ec95ec6fcd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index('ix_contents_user_id')
        batch_op.create_index(batch_op.f('ix_contents_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_user_id'))
        batch_op.create_index('ix_contents_user_id', ['user_id'], unique=True)

    # ### end Alembic commands ###
