"""Make embedding_id nullable in contents table

Revision ID: e4835d7ab10b
Revises: 1f06b2fc9cc2
Create Date: 2025-05-18 23:35:14.986837

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = 'e4835d7ab10b'
down_revision = '1f06b2fc9cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('embedding_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('embedding_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
