"""Removed unique constraint from user_id in query table

Revision ID: fd53eae58bbd
Revises: 3119415bcb82
Create Date: 2025-03-13 13:55:44.136102

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = 'fd53eae58bbd'
down_revision = '3119415bcb82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index('ix_queries_user_id')
        batch_op.create_index(batch_op.f('ix_queries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queries_user_id'))
        batch_op.create_index('ix_queries_user_id', ['user_id'], unique=True)

    # ### end Alembic commands ###
